### ISSUE TITLE
php7 error

### ISSUE THREAD

**Issue by Myer921** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#1]
Fatal error: Uncaught Error: Call to undefined function split() in /vhost/wp-content/pg4wp/driver_pgsql.php:528 Stack trace: #0 /vhost/wp-content/pg4wp/driver_pgsql.php(134): pg4wp_rewrite('INSERT INTO wp_...') #1 /vhost/wp-content/pg4wp/core.php(34) : eval()'d code(1750): wpsql_query('INSERT INTO `wp...', 1) #2 /vhost/wp-content/pg4wp/core.php(34) : eval()'d code(1654): wpdb2->_do_query('INSERT INTO`wp...') #3 /vhost/wp-content/pg4wp/core.php(34) : eval()'d code(1852): wpdb2->query('INSERT INTO `wp...') #4 /vhost/wp-content/pg4wp/core.php(34) : eval()'d code(1780): wpdb2->_insert_replace_helper('wp_usermeta', Array, NULL, 'INSERT') #5 /vhost/wp-includes/meta.php(100): wpdb2->insert('wp_usermeta', Array) #6 /vhost/wp-includes/meta.php(202): add_metadata('user', 1, 'wp_user-setting...', 'mfold=f') #7 /vhost/wp-includes/user.php(1356): update_metadata('user', 1, 'wp_user-setting...', 'mfold=f', '') #8 /vhost/wp-includes/user.php(423): in /vhost/wp-content/pg4wp/driver_pgsql.php on line 528

**Comment by kevinoid** [comment]
Although I've fixed the specific error that you mentioned (`Call to undefined function split()`), I suspect you may encounter more issues using PHP 7.  The code has been unmaintained for quite a while and I doubt anyone has used it, much less thoroughly tested it, on recent versions of PHP.

I also don't want to give the wrong impression.  I'm not looking to take over maintenance of PG4WP.  So issues reported here may or may not get looked at.  But since this one was an easy fix, it seemed worth the effort.  Hope it helps.

**Comment by Myer921** [comment]
Thank you

**Comment by Myer921** [comment]
Forgive me I don't understand PHP
