### ISSUE TITLE
Ability to change on the fly what is used?

### ISSUE THREAD

**Issue by ohioiproject** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#10]
Hello. I know this isn't really what the plugin is for, however is it possible (soon or in the near future) that the plugin could utilise a feature that would allow users to select which they want to use (post-installation) via the plugin, or via the config file?

Further, could the plugin allow load balancing between pgdb and mysql/mariadb (ie: one attempts to help the other balance the load by taking more "strenuous" scripts and letting mysql/mdb run those while less taxing items (browsing, caching, logs, post making, pages, etc.) are handled by a mirrored pgdb service that would allow either to fail and the site to remain functional?

Just a few ideas, I know it's not really being maintained, but it's just food for thought.

Further: If I was to make a new install and just copy all my files and everything, and I DID translate to the pgdb system, would I be hypothetically able to just import my tables into myPGadmin and be up and running?

Thanks,
Joseph

**Comment by kevinoid** [comment]
I'll try to tackle all of your thoughts/questions in turn:

#### Configurable Switching Between MySQL and PostgreSQL

This is not handled really well at the moment.  The plugin allows defining `DB_DRIVER` to either `'mysql'` or `'pgsql'` to switch between MySQL and PostgreSQL databases, but it requires editing `db.php` and doesn't provide any sort of data migration.  (More on that later.)  It could definitely be made better in several ways.

#### Load balancing

Although it would be technically possible to implement various sorts of load balancing, the current performance issues in the plugin mostly rule out its use in any sort of high-load environment.  Even then I would think that you'd have more luck doing the load balancing at the database level and/or at the HTTP level rather than in the PHP code, but I don't have any experience scaling Wordpress so I could be wrong about that.

#### Migrating from MySQL to PostgreSQL

If you export the MySQL database and import into PostgreSQL, then install the pg4wp plugin and configure it to connect to the PostgreSQL database everything should work as expected.  The only complication that I am aware of is that some `datetime` columns use `'0000-00-00 00:00:00'` as the default value, which is invalid in PostgreSQL.  Pg4wp uses `now()` as the default for such fields.

As you noted, the project is not really being maintained, since I didn't write it and don't have the time to rewrite it into a more maintainable form at the moment.  You have raised some good thoughts and questions.  If you'd like to formulate any of them into specific bugs or feature requests, feel free to open issues for each specific bug/request or feel free to reply to this issue for more discussion.

Thanks,
Kevin
