### ISSUE TITLE
missing the PostgreSQL

### ISSUE THREAD

**Issue by teguhsangra** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#11]
i have the issue with PostgreSQL for WordPress (PG4WP)
the issue is : 
Your PHP installation appears to be missing the PostgreSQL extension which is required by WordPress with PG4WP.

can you help me ?

plis help me sir

**Comment by kevinoid** [comment]
The problem is that you are missing the [pgsql PHP extension](http://us1.php.net/manual/en/book.pgsql.php).  How to install it depends on how you installed PHP.  If you installed PHP from a package, there is likely a `php-pgsql` package which can be installed as well.  If you compiled PHP from source, you would need to re-compile to enable the `--with-pgsql` option.  If you are on a shared host where you don't control the installed packages, you would need to enable it in your control panel or contact your hosting provider.
