### ISSUE TITLE
[Stale Issue] WP comment_approved column is varchar and WP expects to be able to check it against an int. 

### ISSUE THREAD

**Issue by omontigny** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#14]
Hi

WP_version : 4.9.6

I have a little problem with comments count  : 

`pg_query(): Query failed: ERROR: operator does not exist: character varying = integer LINE 1: ...wp_comments WHERE user_id = 5 AND comment_approved = 1 ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. in  driver_pgsql.php on line 139
`

The value of comment_approved has to be cast but i didn't find how to do that. 
good syntax is  : SELECT COUNT(*) FROM wp_comments WHERE user_id = 5 AND comment_approved = '1'

Thank you in advance for your help.

Best regards

**Comment by ntninja** [comment]
Hi, just saw your comment here!

The PostgreSQL syntax you're looking for is:

```
SELECT COUNT(*) FROM wp_comments WHERE user_id = 5 AND comment_approved = (SELECT CAST(1 AS character varying));
```

However that won't solve your problem. To fix this, one of the following will be required:

  * Convert the mentioned database column `wp_comments.comment_approved` to the `integer` datatype (if it indeed only contains numerical strings)
  * Add a rewrite rule to [pg4wp/driver_pgsql.php](https://github.com/kevinoid/postgresql-for-wordpress/blob/wordpress4-compat/pg4wp/driver_pgsql.php)

Cheers!

**Comment by omontigny** [comment]
Hi Alexander,

I didn’t have time to check that until this week-end.
I Don’t understand exactly what to do because in  comment_approved column there as some text information as ’trashed’ . 
So I don’t know how to solve it. 
To rewrite a new rule in  pg4wp/driver_pgsql.php is there any documentation ? How can I do that ?

Thank you in advance

**Comment by mattbucci** [comment]
might be interesting to see if this issue still exists

**Comment by mattbucci** [comment]
it looks like from the original issue the failing SQL was `SELECT COUNT(*) FROM wp_comments WHERE user_id = 1 AND comment_approved = 1` and this was failing because comment_approved is not an integer. comment_approved is type "character varying". 

When creating this table In MySQL for some reason this value is normally set to VARCHAR(20)

Ofc we can't compare a string and an int like this directly in postgres so we would have to somehow know that this is a varchar and cast it appropriately but we don't know it's varchar at the time of rewrite. 

Instead we would have to write a specific rewrite for "comment_approved" to catch this exact use case, but as of now I can't find where this SELECT is used. maybe it's no longer done this way in modern WP. I will leave this issue open.

**Comment by mattbucci** [comment]
I thought maybe it might be the case that the original reported issue was that pg4wp was stripping off the single quotes from `SELECT COUNT(*) FROM wp_comments WHERE user_id = 5 AND comment_approved = '1'` as all the instances I see in WP core https://github.com/WordPress/WordPress/blob/0a0b0e91cf118693daceeab4c12211c20c1bb697/wp-includes/class-wp-query.php#L2751C1-L2751C1 use single quotes, but I added a test for this and it's working correctly. I will leave the test in the test suite and close this issue

```

    public function test_it_doesnt_remove_single_quotes() 
    {
        $sql = <<<SQL
            SELECT COUNT(*) FROM wp_comments WHERE user_id = 5 AND comment_approved = '1'
        SQL;

        $expected = <<<SQL
            SELECT COUNT(*) FROM wp_comments WHERE user_id = 5 AND comment_approved = '1'
        SQL;

        $postgresql = pg4wp_rewrite($sql);
        $this->assertSame(trim($expected), trim($postgresql));
    }
```
