### ISSUE TITLE
plugin issue

### ISSUE THREAD

**Issue by ahmedmyahya** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#18]
Hey @kevinoid ,
Thanks for the great work you've done, really apricate it.

I am now trying to install my a fresh instance of WordPress using your plugin and I am trying to connect to my PostgreSQL, however, it keeps giving me (504 Gateway Time-out The server didn't respond in time.), and I confirmed that the DB is up and running using PGAdmin.

it's been really frustrating to make it work for the past days and I apricate your kind support on the matter.

Note:
Am using PostgreSQL on IBM cloud, if that makes a difference :)

**Comment by kevinoid** [comment]
Hi @ahmed-yahya-94,

What makes you think there is an issue in pg4wp that is causing the 504 Gateway Time-out?  Can you provide code+instructions for me to reproduce the error?

**Comment by ahmedmyahya** [comment]
Hey @kevinoid,

[Here](https://drive.google.com/file/d/1qSoBNQ7AGOmMureesA99661Bk25yh1ZB/view?usp=sharing) you can find the code for my WordPress including the plugin.

The issue will be present as soon as you call the WordPress installation process

**Comment by kevinoid** [comment]
Thanks @ahmed-yahya-94.

It looks like the pg4wp code you are using is from the `master` branch, which contains the old code from the original author which stopped working in Wordpress 4, rather than the `wordpress4-compat` branch which contains my work (and is the GitHub default).  I can see how that would be confusing and I'll consider renaming the branches.

However, after updating pg4wp I was still unable to reproduce the `504 Gateway Time-out` error you reported (although I did see some query errors which I'll investigate).  Can you confirm that your code produces a `504 Gateway Time-out` error outside of IBM cloud?

**Comment by ahmedmyahya** [comment]
Hey @kevinoid,

Thank you for having a closer look on my project, just to clarify stuff am using the compat branch code and the problem is still present for some reason. :(

**Comment by mattbucci** [comment]
closing stale issue
