### ISSUE TITLE
Object of class WP_Error could not be converted

### ISSUE THREAD

**Issue by r4cdv** [PostgreSQL-For-Wordpress/postgresql-for-wordpress#7]
URL:   *wp-admin/install.php

HTTP ERROR 500

----------------------------------------
**wp-config.php**
```
<?php
define('DB_NAME', 'on_pg_base');
define('DB_USER', 'on_pg_user');
define('DB_PASSWORD', 'H3b40R0s87');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', '');
define('AUTH_KEY',         '546g65df4gdf4g46df465g');
define('SECURE_AUTH_KEY',  '654gdf654g46df465g645');
define('LOGGED_IN_KEY',    'r8tgh74rth4r6h654rt4h58');
define('NONCE_KEY',        '98qw7e98wqe798qw7e98qw4e');
define('AUTH_SALT',        'd23f4g68fd7g489fd4g654dfg');
define('SECURE_AUTH_SALT', '98er7t97er98g84d6f5g4df4');
define('LOGGED_IN_SALT',   '98r7g654df65g4df65g4fd65g4');
define('NONCE_SALT',       'jk56l4jk56l456jk4l56jk4ljk4');
$table_prefix  = 'site_';
define('WP_DEBUG', false);
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');
require_once(ABSPATH . 'wp-settings.php');
```

**Error log:**
> [Wed Feb 08 22:22:16.304180 2017] [:error] [pid 31024] [client 172.16.67.6:42934] PHP Catchable fatal error:  Object of class WP_Error could not be converted to string in /home/webdev/data/www/on/wp-includes/default-constants.php on line 138

**Comment by kevinoid** [comment]
Thanks for the error report.  What version of Wordpress were you using?  What version of PHP?  I'll see if I can reproduce the error.

**Comment by r4cdv** [comment]
Apache	2.4.6-45.el7.centos
PostgreSQL	postgresql-PostgreSQL 9.2.18 on x86_64
PHP	5.4.16-42.el7
Wordpress wordpress-4.7.2-ru_RU.zip

**Comment by r4cdv** [comment]
Made for you screenshots
https://shot.hsdn.org/brjN5lAv
https://shot.hsdn.org/W4CcmWjG
https://shot.hsdn.org/J8bVOQCV
https://shot.hsdn.org/5EOfAwLs

**Comment by kevinoid** [comment]
Thank you!  That will be very helpful for diagnosing the problem.

**Comment by kevinoid** [comment]
So far I have not had any luck reproducing the issue on my test system (Apache 2.4.10, PHP 5.6.29, Wordpress 4.7.2).  Did the error occur before you were presented with the Installation "Information Needed" page that asks for Site Title, Username, etc.?

To get more debugging information, add/change the following options to `wp-config.php`:
```php
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('PG4WP_DEBUG', true);
```
These require that the PHP process be able to write to `wp-content/debug.log` and `wp-content/pg4wp/logs/*`.  This can be accomplished with:
```sh
mkdir wp-content/pg4wp/logs
chmod a+rwX wp-content/pg4wp/logs
touch wp-content/debug.log
chmod a+rw wp-content/debug.log
```
If you do not have shell access to the server, temporarily adding global write permission to wp-content would also be sufficient.

Then visit the site to provoke the error again.  Afterwards, review `wp-content/debug.log` and `wp-content/pg4wp/logs/pg4wp_errors.log`.  They may have many `ERROR:  relation "..." does not exist` errors due to the database not being initialized.  These should be safe to ignore.  Are there any other errors?  Alternatively, if you can post the files somewhere, that would work too.

**Comment by r4cdv** [comment]
The error occurred right at the start of installing WordPress. The site title and other settings I can't assign.


added line in file wp-config:
`define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('PG4WP_DEBUG', true);
define( 'PG4WP_LOG_ERRORS', true);`

result
files:
**pg4wp_SELECT.log**
```
[1486595269.4343] Converting :
SELECT @@SESSION.sql_mode
---- to ----
SELECT ''
---------------------

```
**pg4wp_unmodified.log**
```
[1486595269.4339] SET NAMES 'utf8'
---------------------
[1486595269.4385] SELECT option_name, option_value FROM site_options WHERE autoload = 'yes'
---------------------

```
**debug.log**
```
[08-Feb-2017 23:07:49 UTC] PHP Notice:  Constant PG4WP_DEBUG already defined in /home/webdev/data/www/on/wp-content/db.php on line 18
[08-Feb-2017 23:07:49 UTC] PHP Notice:  Constant PG4WP_LOG_ERRORS already defined in /home/webdev/data/www/on/wp-content/db.php on line 21
[08-Feb-2017 23:07:49 UTC] PHP Catchable fatal error:  Object of class WP_Error could not be converted to string in /home/webdev/data/www/on/wp-includes/default-constants.php on line 138

```
I have written to you the letter on email. Ready to provide you with online viewing and follow your instructions. I Can provide you remote access to my PC via TeamViewer
